apiVersion: v1
kind: Service
metadata:
  name: ephemeral-relay-service
spec:
  selector:
    app: ephemeral-relay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer